### PR TITLE
Made highlight color customizable

### PR DESCRIPTION
**Pull request by hugoh**
Example:

zstyle ":history-search-multi-word" highlight-color "fg=white"

### CODE REVIEW

**Comment by psprint** [comment]
Thanks!

**Comment by psprint** [comment]
I've added third license to the project ( https://github.com/psprint/history-search-multi-word/blob/master/LICENSE_zaw ), can I ask you for permission to cover your contributions with this license?

**Comment by hugoh** [comment]
Sure, no problem.

**Comment by psprint** [comment]
Thanks!

**Pull request merged**
