### PR TITLE
get real path to the plugin.zsh

### PR DESCRIPTION
**Pull request by lexinator**
- this is required if using symlink to this file

### CODE REVIEW

**Comment by psprint** [comment]
I saw that one other project uses this. Can I ask you what are the drawbacks of not using `:A`?

**Comment by lexinator** [comment]
it uses the directory where the symlink is located rather than the real directory where the code is.

**Comment by psprint** [comment]
What drawbacks can not using `:A` cause? Because symlinked directory is still a valid path. But you say you symlink .plugin.zsh file?

**Comment by lexinator** [comment]
```
% mkdir -p /tmp/c/symlink
% cd /tmp/c
% git clone -q https://github.com/psprint/history-search-multi-word.git
% ln -s ../history-search-multi-word/history-search-multi-word.plugin.zsh symlink
sequel% . symlink/history-search-multi-word.plugin.zsh
sequel% <ctrl-r>
zsh:7: history-search-multi-word: function definition file not found
```

**Comment by danielshahaf** [comment]
Using `:A` would cause breakage if `/tmp/c/symlink` were a symlink whose target included `..` components.  The right thing to do would be to use the upcoming `:P` modifier], or `realpath(1)`.

**Comment by lexinator** [comment]
@danielshahaf you mean if there's a symlink to another symlink?

i can switch to :P, but what's the behavior on pre 5.3 when this setting is encountered?

**Comment by danielshahaf** [comment]
No, I mean `ln -s foo/../bar baz`.

```zsh
% foo=$PWD /usr/bin/zsh -fc 'echo $foo:P'
/home/daniel:P
% foo=$PWD /usr/bin/zsh -fc 'echo ${foo:P}'
zsh:1: unrecognized modifier `P'
````

Excuse brevity.

**Comment by lexinator** [comment]
```
% mkdir -p /tmp/$$/{bar,foo}
% cd /tmp/$$
% ln -s foo/../bar baz
% SYMLINK=/tmp/$$/baz
```
The same output for ZSH_VERSION = a62e164, and 5.2
```
% echo ${SYMLINK:A}
/private/tmp/543/bar
```
only works on > 5.2
```
% echo ${SYMLINK:P}
/private/tmp/543/bar
```

**Comment by danielshahaf** [comment]
Right, my description wasn't specific enough.  The issue with `:A` is when a symlink's target contains `foo/..` sequence occurs with `foo` a symlink.

Apologies for the delay.

**Comment by lexinator** [comment]
i still can't decipher your description where the issue is.  It sounds like multiple symlinks that involve ".."?

My change is at least an improvement over now, and when 5.3 is more widespread it can change to :P.

**Comment by danielshahaf** [comment]
> My change is at least an improvement over now, and when 5.3 is more widespread it can change to :P.

If you want portability then `cd foo && pwd -P` should work in pre-5.3 too.

As to the difference between :A and :P, the short version is that
${foo:P} is equivalent to realpath($foo) always, and ${foo:A} is
equivalent to realpath($foo) only in some cases.  The 5.3 manual
explains the differences in more detail.

**Comment by lexinator** [comment]
works for me.  updated PR per https://github.com/psprint/history-search-multi-word/pull/5#issuecomment-270811207

**Comment by lexinator** [comment]
hmm. the suggested approach doesn't work as "foo" is the directory containing the symlink which is the current behavior without this PR.

At this point I will stick to my approach and close this PR.

thanks

**Pull request closed without merging**
